### PR TITLE
Lost and Found Logo

### PR DESCRIPTION
**Pull request by Koshal7**
Issue: 91

### CODE REVIEW

**Comment by nityagupta6** [comment]
The idea is nice but it looks a bit weird as a logo...think by your self if this was the logo of a service provider company...it would be a bit weird right?
Pls improvise on the logo and comment here for review.

**Comment by Koshal7** [comment]
@nityagupta6 you are right, i will change the logo

**Comment by Koshal7** [comment]
@nityagupta6 pls review

**Comment by nityagupta6** [comment]
nicee!!

**Pull request merged**
