### PR TITLE
Task 2 done

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 31

### CODE REVIEW

**Comment by nityagupta6** [comment]
A lot of improvements have to be done...Firstly use Figma mirror and select your desktop frame and see how the frame really looks on the PC, you will get to know many changes by yourself. The entire page has to be scaled to an appropriate size, meaning the elements of the page should be in the proper ratio with the page size. Make the page look more appealing, use vectors and graphics. Add more features to the hero section. Make proper alignments on the page.

**Comment by nityagupta6** [comment]
Once you have redesigned h=the page comment here for reviewing.

**Comment by SanyamAgrawal07** [comment]
@nityagupta6 please review it now(I had to add a sample image coz the homepage and other pages arent designed yet)

**Comment by nityagupta6** [comment]
good job

**Pull request merged**
