### PR TITLE
Create anshgeez31.txt

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 67
image

### CODE REVIEW

**Comment by nityagupta6** [comment]
Good try...but pls add logo of campus olx, and make the subscribe section a bit small as in it should look in proper ratio to the footer, and make it the footer corresponding to the hero section you had made. When these changes are done comment here for review.

**Comment by anshgeez31** [comment]
@nityagupta6 Done some changes. Now please have a look once again.

**Comment by nityagupta6** [comment]
Nicee...Final changes to be done are add the campusOLX logo in the footer...and shift the social media handle icons such that they align properly with write to us heading. For adding logo make sure the alignment and spacing are taken care of and shifting of all sections is done properly...once these changes are done comment here s that I could merge.

**Comment by nityagupta6** [comment]
Good work

**Pull request merged**
