### PR TITLE
issue :5 side task completed

### PR DESCRIPTION
**Pull request by prathambhatia86**
Issue: 5

### CODE REVIEW

**Comment by nityagupta6** [comment]
The task is well done!!...just that the changes you mentioned in the first screen arent to the point or the exact reasons why the design would have poor ux. Pls go through the first task again and suggest better changes. Once done pls mention here in the comments so that I could review the changes and merge the PR. No need to make new pr just make the changes in the file and comment here or dm on discord.

**Comment by prathambhatia86** [comment]
please review the added point.Do let me know if more changes are needed.

**Comment by nityagupta6** [comment]
pls follow the PR template...else points wont get added even if I merge

**Comment by nityagupta6** [comment]
once done comment here...I will merge the PR

**Comment by prathambhatia86** [comment]
I have changed it to correct template.

**Comment by nityagupta6** [comment]
well done!

**Pull request merged**
