### PR TITLE
Footer for website

### PR DESCRIPTION
**Pull request by JahnaviGadde**
Issue: 67

### CODE REVIEW

**Comment by nityagupta6** [comment]
Amazing efforts...good work!...Just one improvisation the call to action buttons should not be in the footer...so the sign in and sign up button should not be present in the footer rest is amazing...pls do the required changes. and comment here for merge.

**Comment by JahnaviGadde** [comment]
Updated the design with the changes you mentioned.

**Comment by nityagupta6** [comment]
One more change...pls place all the sections at an equal spacing from the right margin, as in shift campus olx wala section and about us wala section to the right towards follow us, and keep the spacing between campusolx and follow us same as the spacing between campusolx and about us. Once these changes are made comment here for merge.

**Comment by JahnaviGadde** [comment]
done 👍

**Comment by nityagupta6** [comment]
Nicee Efforts!!

**Pull request merged**
