### PR TITLE
Create kushal7201.txt

### PR DESCRIPTION
**Pull request by kushal7201**
Issue: 90

### CODE REVIEW

**Comment by kushal7201** [comment]
I had completed this task before without knowing that it was closed some hours before. Could you please accept that as I have worked hard to complete it. I was not able to do it before because of exams. I would be very thankful to you.

**Comment by nityagupta6** [comment]
Have you created a separate PR for fun task??

**Comment by kushal7201** [comment]
No
I am unable to do that

**Comment by nityagupta6** [comment]
okk wait first let me merge this PR then make a new PR for the ffun task okk?

**Comment by nityagupta6** [comment]
Good Work...just keep one thing in mind from the next time...instead of using images use iconify plugin for icons

**Comment by kushal7201** [comment]
Thankyou ma'am. I don't know how to iconify the icons.

**Pull request merged**
