### PR TITLE
Task 4 Footer

### PR DESCRIPTION
**Pull request by Koshal7**
Issue: 67

### CODE REVIEW

**Comment by Koshal7** [comment]
done, @nityagupta6 pls review

**Comment by nityagupta6** [comment]
yeah now you have made the margins perfect, but the spacing between individual sections is not equal, So for that, place all the sections like social media, contacts, service, and support at equal spacing starting from the right margin

**Comment by nityagupta6** [comment]
Once changes are made comment for merge.

**Comment by Koshal7** [comment]
yeah done, you can merge it now @nityagupta6

**Comment by nityagupta6** [comment]
Perfect Great Work!!

**Pull request merged**
