### PR TITLE
Hero section added

### PR DESCRIPTION
**Pull request by humbleshashi8104**
issue: 31
added a figma file in .txt format , for the hero section page required.

### CODE REVIEW

**Comment by humbleshashi8104** [comment]
@nityagupta6  ,please have a look at my PR

**Comment by nityagupta6** [comment]
yes reviewing rn

**Comment by nityagupta6** [comment]
join the discord vc

**Comment by nityagupta6** [comment]
i have to tell u the errors in your design

**Comment by humbleshashi8104** [comment]
Can I join it after 2-3 hours, I'm out of station and travelling through train rt now, please if u can manage i will be very glad.

**Pull request merged**
